name: Build and Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - production

jobs:
  build:

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: production

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install SCSS Compiler and Bootstrap
        run: npm install

      - name: Compile SCSS
        run: npm run sass

      - name: Bust Cache
        run: npm run cache-busting

      - uses: actions/upload-artifact@master
        with:
          name: page
          path: |
            ./
            !./node_modules/*
          if-no-files-found: error
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    steps:
    - uses: actions/download-artifact@master
      with:
        name: page
        path: .
    - uses: actions/configure-pages@v1
    - uses: actions/upload-pages-artifact@v3
      with:
        path: .
    - id: deployment
      uses: actions/deploy-pages@main
